import { readdirSync, statSync } from "fs";
import { join } from "path";

const commandsDir = join(process.cwd(), "commands");
const outputFile = join(commandsDir, "registry.ts");

console.log("Generating command registry...");

const items = readdirSync(commandsDir);
const commands: string[] = [];

for (const item of items) {
  const itemPath = join(commandsDir, item);
  if (statSync(itemPath).isDirectory()) {
    if (readdirSync(itemPath).includes("index.ts")) {
        commands.push(item);
    }
  }
}

const imports = commands.map(cmd => `import * as ${cmd.replace(/-/g, '_')} from "./${cmd}/index";`).join("\n");
const exports = `export const CommandRegistry: Record<string, any> = {\n` + 
  commands.map(cmd => `  "${cmd}": ${cmd.replace(/-/g, '_')},`).join("\n") + 
  `\n};\n`;

const content = `// Auto-generated by utils/generate-registry.ts
// Do not edit manually.
${imports}

${exports}
`;

await Bun.write(outputFile, content);
console.log(`✅ Registry generated at ${outputFile}`);