import { readdirSync, statSync, existsSync, readFileSync } from "fs";
import { join } from "path";

const commandsDir = join(process.cwd(), "commands");
const pdCommandsDir = join(process.cwd(), "../../apps/page-designer/commands");

// Commands that are top-level in the unified `belz` binary
const TOP_LEVEL_COMMANDS = new Set(["migrate", "envs"]);

console.log("Generating command registries...");

function discoverCommands(dir: string): string[] {
  try {
    const items = readdirSync(dir);
    const commands: string[] = [];
    for (const item of items) {
      const itemPath = join(dir, item);
      if (statSync(itemPath).isDirectory()) {
        if (readdirSync(itemPath).includes("index.ts")) {
          commands.push(item);
        }
      }
    }
    return commands;
  } catch {
    return [];
  }
}

function readHelpText(dir: string, cmd: string): string | null {
  const p = join(dir, cmd, "help.txt");
  if (existsSync(p)) return readFileSync(p, "utf8").trimEnd();
  return null;
}

function buildHelpMap(commands: string[], dir: string): string {
  const entries = commands
    .map(cmd => {
      const text = readHelpText(dir, cmd);
      return text != null
        ? `  "${cmd}": ${JSON.stringify(text)},`
        : null;
    })
    .filter(Boolean);
  return `{\n${entries.join("\n")}\n}`;
}

const allAdCommands = discoverCommands(commandsDir);
const adCommands = allAdCommands.filter(cmd => !TOP_LEVEL_COMMANDS.has(cmd));
const topLevelCommands = allAdCommands.filter(cmd => TOP_LEVEL_COMMANDS.has(cmd));
const pdCommands = discoverCommands(pdCommandsDir);

function toIdentifier(cmd: string) {
  return cmd.replace(/-/g, "_");
}

// ── registry-ad.ts ───────────────────────────────────────────────────────────
const adImports = adCommands
  .map(cmd => `import * as ${toIdentifier(cmd)} from "./${cmd}/index";`)
  .join("\n");
const adRegistry =
  `export const ADCommandRegistry: Record<string, any> = {\n` +
  adCommands.map(cmd => `  "${cmd}": ${toIdentifier(cmd)},`).join("\n") +
  `\n};\n`;

const adContent = `// Auto-generated by utils/generate-registry.ts
// Do not edit manually.
${adImports}

${adRegistry}`;

// ── registry-pd.ts ───────────────────────────────────────────────────────────
const pdImports = pdCommands
  .map(cmd => `import * as ${toIdentifier(cmd)} from "../../page-designer/commands/${cmd}/index";`)
  .join("\n");
const pdRegistry =
  `export const PDCommandRegistry: Record<string, any> = {\n` +
  pdCommands.map(cmd => `  "${cmd}": ${toIdentifier(cmd)},`).join("\n") +
  `\n};\n`;

const pdContent = `// Auto-generated by utils/generate-registry.ts
// Do not edit manually.
${pdImports}

${pdRegistry}`;

// ── registry-top.ts ──────────────────────────────────────────────────────────
const topImports = topLevelCommands
  .map(cmd => `import * as ${toIdentifier(cmd)} from "./${cmd}/index";`)
  .join("\n");
const topRegistry =
  `export const TopLevelCommandRegistry: Record<string, any> = {\n` +
  topLevelCommands.map(cmd => `  "${cmd}": ${toIdentifier(cmd)},`).join("\n") +
  `\n};\n`;

const topContent = `// Auto-generated by utils/generate-registry.ts
// Do not edit manually.
${topImports}

${topRegistry}`;

// ── registry.ts (legacy backward-compat re-export) ───────────────────────────
const allCommands = [...adCommands, ...topLevelCommands];
const legacyImports = allCommands
  .map(cmd => `import * as ${toIdentifier(cmd)} from "./${cmd}/index";`)
  .join("\n");
const legacyRegistry =
  `export const CommandRegistry: Record<string, any> = {\n` +
  allCommands.map(cmd => `  "${cmd}": ${toIdentifier(cmd)},`).join("\n") +
  `\n};\n`;

const legacyContent = `// Auto-generated by utils/generate-registry.ts
// Do not edit manually.
// Legacy registry — all AD + top-level commands for backward compatibility.
${legacyImports}

${legacyRegistry}`;

// ── registry-help.ts (embedded help text for compiled binary) ────────────────
const adHelpMap = buildHelpMap(adCommands, commandsDir);
const pdHelpMap = buildHelpMap(pdCommands, pdCommandsDir);
const topHelpMap = buildHelpMap(topLevelCommands, commandsDir);

const helpContent = `// Auto-generated by utils/generate-registry.ts
// Do not edit manually.
// Embedded help text for use in compiled binary (no filesystem access needed).

export const ADHelpMap: Record<string, string> = ${adHelpMap};

export const PDHelpMap: Record<string, string> = ${pdHelpMap};

export const TopHelpMap: Record<string, string> = ${topHelpMap};

export function makeHelpResolver(map: Record<string, string>) {
  return async (cmd: string): Promise<string | null> => map[cmd] ?? null;
}
`;

await Bun.write(join(commandsDir, "registry-ad.ts"), adContent);
await Bun.write(join(commandsDir, "registry-pd.ts"), pdContent);
await Bun.write(join(commandsDir, "registry-top.ts"), topContent);
await Bun.write(join(commandsDir, "registry.ts"), legacyContent);
await Bun.write(join(commandsDir, "registry-help.ts"), helpContent);

console.log(`✅ registry-ad.ts   (${adCommands.length} AD commands: ${adCommands.join(", ")})`);
console.log(`✅ registry-pd.ts   (${pdCommands.length} PD commands: ${pdCommands.join(", ")})`);
console.log(`✅ registry-top.ts  (${topLevelCommands.length} top-level commands: ${topLevelCommands.join(", ")})`);
console.log(`✅ registry-help.ts (embedded help text for ${adCommands.length + pdCommands.length + topLevelCommands.length} commands)`);
console.log(`✅ registry.ts      (legacy backward-compat)`);
