// Auto-generated by utils/generate-registry.ts
// Do not edit manually.
import * as fetch_method from "./fetch-method/index";
import * as envs from "./envs/index";
import * as run_suites from "./run-suites/index";
import * as save_suite from "./save-suite/index";
import * as show_method from "./show-method/index";
import * as run_method from "./run-method/index";
import * as test_method from "./test-method/index";

export const CommandRegistry: Record<string, any> = {
  "fetch-method": fetch_method,
  "envs": envs,
  "run-suites": run_suites,
  "save-suite": save_suite,
  "show-method": show_method,
  "run-method": run_method,
  "test-method": test_method,
};

