// Auto-generated by utils/generate-registry.ts
// Do not edit manually.
import * as comments from "../../teamwork/commands/comments/index";
import * as task from "../../teamwork/commands/task/index";

export const TWCommandRegistry: Record<string, any> = {
  "comments": comments,
  "task": task,
};
