// Auto-generated by utils/generate-registry.ts
// Do not edit manually.
import * as run from "../../automation-designer/commands/run/index";
import * as test from "../../automation-designer/commands/test/index";
import * as run_suites from "../../automation-designer/commands/run-suites/index";
import * as save_suite from "../../automation-designer/commands/save-suite/index";
import * as get from "../../automation-designer/commands/get/index";
import * as sql from "../../automation-designer/commands/sql/index";
import * as show from "../../automation-designer/commands/show/index";

export const ADCommandRegistry: Record<string, any> = {
  "run": run,
  "test": test,
  "run-suites": run_suites,
  "save-suite": save_suite,
  "get": get,
  "sql": sql,
  "show": show,
};
