// Auto-generated by utils/generate-registry.ts
// Do not edit manually.
import * as envs from "./envs/index";
import * as migrate_legacy from "./migrate-legacy/index";
import * as config from "./config/index";
import * as web from "./web/index";

export const TopLevelCommandRegistry: Record<string, any> = {
  "envs": envs,
  "migrate-legacy": migrate_legacy,
  "config": config,
  "web": web,
};
