// Auto-generated by utils/generate-registry.ts
// Do not edit manually.
import * as freeze from "../../integrations/release/commands/freeze/index";
import * as matrix from "../../integrations/release/commands/matrix/index";

export const ReleaseCommandRegistry: Record<string, any> = {
  "freeze": freeze,
  "matrix": matrix,
};
