// Auto-generated by utils/generate-registry.ts
// Do not edit manually.
// Legacy registry — all AD + top-level commands for backward compatibility.
import * as run from "./run/index";
import * as test from "./test/index";
import * as run_suites from "./run-suites/index";
import * as save_suite from "./save-suite/index";
import * as get from "./get/index";
import * as sql from "./sql/index";
import * as show from "./show/index";
import * as envs from "./envs/index";
import * as migrate from "./migrate/index";

export const CommandRegistry: Record<string, any> = {
  "run": run,
  "test": test,
  "run-suites": run_suites,
  "save-suite": save_suite,
  "get": get,
  "sql": sql,
  "show": show,
  "envs": envs,
  "migrate": migrate,
};
