// Auto-generated by utils/generate-registry.ts
// Do not edit manually.
import * as envs from "./envs/index";
import * as config from "./config/index";
import * as migrate from "./migrate/index";

export const TopLevelCommandRegistry: Record<string, any> = {
  "envs": envs,
  "config": config,
  "migrate": migrate,
};
