// Auto-generated by utils/generate-registry.ts
// Do not edit manually.
import * as run from "../../migrations/commands/run/index";
import * as log from "../../migrations/commands/log/index";
import * as profiles from "../../migrations/commands/profiles/index";
import * as status from "../../migrations/commands/status/index";

export const MigrateCommandRegistry: Record<string, any> = {
  "run": run,
  "log": log,
  "profiles": profiles,
  "status": status,
};
