// CSS generator — turns the token objects into a :root custom-property block.
//
// The output (dist/theme.css) is the artifact the web app and the extension
// both consume. It carries values only — no @font-face (font loading differs
// per surface) and no component rules.

import { palette, radius, space, fontSize, fontFamily, motion } from "./tokens";
import { role } from "./color";

const kebab = (s: string): string =>
  s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

/** Generate the `:root { --belz-* }` stylesheet. */
export function generateThemeCss(): string {
  const out: string[] = [];
  out.push("/* GENERATED by @belzabar/design — do not edit by hand.");
  out.push("   Regenerate with: bun run --filter @belzabar/design build */");
  out.push(":root {");

  out.push("  /* palette */");
  for (const [k, v] of Object.entries(palette)) {
    out.push(`  --belz-${kebab(k)}: ${v};`);
  }

  out.push("  /* semantic roles */");
  for (const [k, v] of Object.entries(role)) {
    out.push(`  --belz-role-${kebab(k)}: ${v};`);
  }

  out.push("  /* radius — one sharp value */");
  out.push(`  --belz-radius: ${radius.none};`);

  out.push("  /* spacing */");
  for (const [k, v] of Object.entries(space)) {
    out.push(`  --belz-space-${k}: ${v};`);
  }

  out.push("  /* type */");
  for (const [k, v] of Object.entries(fontSize)) {
    out.push(`  --belz-text-${k}: ${v};`);
  }
  out.push(`  --belz-font-mono: ${fontFamily.mono};`);

  out.push("  /* motion */");
  for (const [k, v] of Object.entries(motion)) {
    out.push(`  --belz-motion-${k}: ${v};`);
  }

  out.push("}");
  out.push("");
  return out.join("\n");
}
