// Auto-generated by utils/generate-registry.ts
// Do not edit manually.
import * as analyze from "./analyze/index";
import * as show_page from "./show-page/index";
import * as show_component from "./show-component/index";
import * as find_ad_methods from "./find-ad-methods/index";

export const CommandRegistry: Record<string, any> = {
  "analyze": analyze,
  "show-page": show_page,
  "show-component": show_component,
  "find-ad-methods": find_ad_methods,
};

