import { readdirSync, statSync, existsSync, readFileSync } from "fs";
import { join } from "path";

const adCommandsDir = join(process.cwd(), "../automation-designer/commands");
const topCommandsDir = join(process.cwd(), "commands"); // cli/commands/ (envs, migrate)
const pdCommandsDir = join(process.cwd(), "../page-designer/commands");
const twCommandsDir = join(process.cwd(), "../teamwork/commands");

console.log("Generating command registries...");

function discoverCommands(dir: string): string[] {
  try {
    const items = readdirSync(dir);
    const commands: string[] = [];
    for (const item of items) {
      const itemPath = join(dir, item);
      if (statSync(itemPath).isDirectory()) {
        if (readdirSync(itemPath).includes("index.ts")) {
          commands.push(item);
        }
      }
    }
    return commands;
  } catch {
    return [];
  }
}

function readHelpText(dir: string, cmd: string): string | null {
  const p = join(dir, cmd, "help.txt");
  if (existsSync(p)) return readFileSync(p, "utf8").trimEnd();
  return null;
}

function readDescText(dir: string, cmd: string): string | null {
  const p = join(dir, cmd, "desc.txt");
  if (existsSync(p)) return readFileSync(p, "utf8").trimEnd();
  return null;
}

function buildHelpFull(sections: Array<{ header: string; commands: string[]; dir: string }>): string {
  const RULE = "─".repeat(77);
  const lines = [
    "NOTE FOR LLM AGENTS: Always use the --llm flag for structured, parseable output.",
    "  Example: belz ad show <uuid> --llm",
    "",
    "belz — Belzabar CLI",
  ];

  for (const section of sections) {
    lines.push("", section.header, RULE);
    for (const cmd of section.commands) {
      const desc = readDescText(section.dir, cmd);
      if (desc) {
        lines.push(desc, "");
      }
    }
  }

  lines.push("Use 'belz <namespace> <cmd> --help' for full flag documentation and examples.");
  return lines.join("\n");
}

function buildHelpMap(commands: string[], dir: string): string {
  const entries = commands
    .map(cmd => {
      const text = readHelpText(dir, cmd);
      return text != null
        ? `  "${cmd}": ${JSON.stringify(text)},`
        : null;
    })
    .filter(Boolean);
  return `{\n${entries.join("\n")}\n}`;
}

const adCommands = discoverCommands(adCommandsDir);
const topLevelCommands = discoverCommands(topCommandsDir);
const pdCommands = discoverCommands(pdCommandsDir);
const twCommands = discoverCommands(twCommandsDir);

// JS reserved words and globals that would collide with an `import * as X`
// alias. Prefix such identifiers with `cmd_` so the generated source is valid.
const RESERVED = new Set([
  "break", "case", "catch", "class", "const", "continue", "debugger",
  "default", "delete", "do", "else", "enum", "export", "extends", "false",
  "finally", "for", "function", "if", "implements", "import", "in",
  "instanceof", "interface", "let", "new", "null", "package", "private",
  "protected", "public", "return", "super", "switch", "static", "this",
  "throw", "true", "try", "typeof", "var", "void", "while", "with", "yield",
  "await", "async", "categories",
]);

function toIdentifier(cmd: string) {
  const raw = cmd.replace(/-/g, "_");
  if (RESERVED.has(raw) || /^\d/.test(raw)) return `cmd_${raw}`;
  return raw;
}

// ── registry-ad.ts ───────────────────────────────────────────────────────────
const adImports = adCommands
  .map(cmd => `import * as ${toIdentifier(cmd)} from "../../automation-designer/commands/${cmd}/index";`)
  .join("\n");
const adRegistry =
  `export const ADCommandRegistry: Record<string, any> = {\n` +
  adCommands.map(cmd => `  "${cmd}": ${toIdentifier(cmd)},`).join("\n") +
  `\n};\n`;

const adContent = `// Auto-generated by utils/generate-registry.ts
// Do not edit manually.
${adImports}

${adRegistry}`;

// ── registry-pd.ts ───────────────────────────────────────────────────────────
const pdImports = pdCommands
  .map(cmd => `import * as ${toIdentifier(cmd)} from "../../page-designer/commands/${cmd}/index";`)
  .join("\n");
const pdRegistry =
  `export const PDCommandRegistry: Record<string, any> = {\n` +
  pdCommands.map(cmd => `  "${cmd}": ${toIdentifier(cmd)},`).join("\n") +
  `\n};\n`;

const pdContent = `// Auto-generated by utils/generate-registry.ts
// Do not edit manually.
${pdImports}

${pdRegistry}`;

// ── registry-tw.ts ───────────────────────────────────────────────────────────
const twImports = twCommands
  .map(cmd => `import * as ${toIdentifier(cmd)} from "../../teamwork/commands/${cmd}/index";`)
  .join("\n");
const twRegistry =
  `export const TWCommandRegistry: Record<string, any> = {\n` +
  twCommands.map(cmd => `  "${cmd}": ${toIdentifier(cmd)},`).join("\n") +
  `\n};\n`;

const twContent = `// Auto-generated by utils/generate-registry.ts
// Do not edit manually.
${twImports}

${twRegistry}`;

// ── registry-top.ts ──────────────────────────────────────────────────────────
const topImports = topLevelCommands
  .map(cmd => `import * as ${toIdentifier(cmd)} from "./${cmd}/index";`)
  .join("\n");
const topRegistry =
  `export const TopLevelCommandRegistry: Record<string, any> = {\n` +
  topLevelCommands.map(cmd => `  "${cmd}": ${toIdentifier(cmd)},`).join("\n") +
  `\n};\n`;

const topContent = `// Auto-generated by utils/generate-registry.ts
// Do not edit manually.
${topImports}

${topRegistry}`;

// ── registry-help.ts (embedded help text for compiled binary) ────────────────
const adHelpMap = buildHelpMap(adCommands, adCommandsDir);
const pdHelpMap = buildHelpMap(pdCommands, pdCommandsDir);
const twHelpMap = buildHelpMap(twCommands, twCommandsDir);
const topHelpMap = buildHelpMap(topLevelCommands, topCommandsDir);

const helpFullText = buildHelpFull([
  { header: "belz ad <cmd>  —  Automation Designer", commands: adCommands,       dir: adCommandsDir },
  { header: "belz pd <cmd>  —  Page Designer",       commands: pdCommands,       dir: pdCommandsDir },
  { header: "belz tw <cmd>  —  Teamwork",            commands: twCommands,       dir: twCommandsDir },
  { header: "belz <cmd>  —  Top-level",              commands: topLevelCommands, dir: topCommandsDir },
]);

const helpContent = `// Auto-generated by utils/generate-registry.ts
// Do not edit manually.
// Embedded help text for use in compiled binary (no filesystem access needed).

export const ADHelpMap: Record<string, string> = ${adHelpMap};

export const PDHelpMap: Record<string, string> = ${pdHelpMap};

export const TWHelpMap: Record<string, string> = ${twHelpMap};

export const TopHelpMap: Record<string, string> = ${topHelpMap};

export const HELP_FULL_TEXT: string = ${JSON.stringify(helpFullText)};

export function makeHelpResolver(map: Record<string, string>) {
  return async (cmd: string): Promise<string | null> => map[cmd] ?? null;
}
`;

await Bun.write(join(topCommandsDir, "registry-ad.ts"), adContent);
await Bun.write(join(topCommandsDir, "registry-pd.ts"), pdContent);
await Bun.write(join(topCommandsDir, "registry-tw.ts"), twContent);
await Bun.write(join(topCommandsDir, "registry-top.ts"), topContent);
await Bun.write(join(topCommandsDir, "registry-help.ts"), helpContent);

console.log(`✅ registry-ad.ts   (${adCommands.length} AD commands: ${adCommands.join(", ")})`);
console.log(`✅ registry-pd.ts   (${pdCommands.length} PD commands: ${pdCommands.join(", ")})`);
console.log(`✅ registry-tw.ts   (${twCommands.length} TW commands: ${twCommands.join(", ")})`);
console.log(`✅ registry-top.ts  (${topLevelCommands.length} top-level commands: ${topLevelCommands.join(", ")})`);
console.log(`✅ registry-help.ts (embedded help text for ${adCommands.length + pdCommands.length + twCommands.length + topLevelCommands.length} commands)`);
